WIP: Upgrade to Solarium 6
mkalkbrenner/search_api_solr pull request #62
Opened 2021-01-12 18:15 UTC by japerry

Testing the Solarium 6 upgrade. Making PR now to test actions.

2021-01-18 15:02 UTC, mkalkbrenner requested changes
Most things in this draft are not required for porting Search API Solr 8.x-1.x to Solarium 6.x.

2021-01-18 15:02 UTC, mkalkbrenner commented on search_api_solr.install
> +        'description' => t('Community support of Search API Solr 1.x Ends 2020-12-31. Please contact Acquia support to report any issues with this module.'),
This is not true. The community support has been extended throughout 2021.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/Solarium/Autocomplete/Query.php
> +class Query extends AbstractQuery implements ComponentAwareQueryInterface {
This class is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/Solarium/Autocomplete/RequestBuilder.php
> +class RequestBuilder extends AbstractRequestBuilder {
This class is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/Solarium/Autocomplete/ResponseParser.php
> +class ResponseParser extends AbstractResponseParser implements ResponseParserInterface {
This class is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/Solarium/Autocomplete/Result.php
> +class Result extends BaseResult {
This class is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/Solarium/Result/StreamDocument.php
> +class StreamDocument extends AbstractDocument {
This class is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  const SEARCH_API_SOLR_MIN_SCHEMA_VERSION = '4.1.1';
Not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  const SEARCH_API_SOLR_LANGUAGE_SEPARATOR = ';';
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getLanguageSpecificSolrFieldNames($language_id, ?IndexInterface $index, $reset = FALSE);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getSolrFieldNamesKeyedByLanguage(array $language_ids, IndexInterface $index, $reset = FALSE);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getDomain();
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getEnvironment();
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function isManagedSchema();
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function isOptimizeEnabled();
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getIndexFilterQueryString(IndexInterface $index);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getCollectionEndpoint(IndexInterface $index);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getIndexSolrSettings(IndexInterface $index);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getIndexId(IndexInterface $index);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getTargetedIndexId(IndexInterface $index);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getTargetedSiteHash(IndexInterface $index);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function executeStreamingExpression(QueryInterface $query);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function executeGraphStreamingExpression(QueryInterface $query);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function finalizeIndex(IndexInterface $index);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getSchemaLanguageStatistics(?Endpoint $endpoint = NULL);
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getDocumentCounts();
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getMaxDocumentVersions();
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getDisabledFieldTypes(): array;
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getDisabledCaches(): array;
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getDisabledRequestHandlers(): array;
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function getDisabledRequestDispatchers(): array;
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrBackendInterface.php
> +  public function isNonDrupalOrOutdatedConfigSetAllowed(): bool;
This is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-18 15:02 UTC, mkalkbrenner commented on src/SolrCloudConnectorInterface.php
> +interface SolrCloudConnectorInterface extends SolrConnectorInterface {
This class is not needed to migrate Search API Solr 8.x-1.x to Solarium 6.

2021-01-22 12:33 UTC, narendradesai commented
Thank you Markus, your comments were very helpful. Will update PR accordingly.

2021-01-25 18:02 UTC, closed without merging